//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Tools.WindowsInstallerXml.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HeatStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HeatStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Tools.WindowsInstallerXml.Tools.HeatStrings", typeof(HeatStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  usage:  heat.exe harvestType harvestSource &lt;harvester arguments&gt; -o[ut] sourceFile.wxs
        ///
        ///Supported harvesting types:
        ///.
        /// </summary>
        internal static string HelpMessageBegin {
            get {
                return ResourceManager.GetString("HelpMessageBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;extension&gt;  extension assembly or &quot;class, assembly&quot;.
        /// </summary>
        internal static string HelpMessageExtension {
            get {
                return ResourceManager.GetString("HelpMessageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indentation multiple (overrides default of 4).
        /// </summary>
        internal static string HelpMessageIndentation {
            get {
                return ResourceManager.GetString("HelpMessageIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip printing heat logo information.
        /// </summary>
        internal static string HelpMessageNoLogo {
            get {
                return ResourceManager.GetString("HelpMessageNoLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    {0,-7}  {1}.
        /// </summary>
        internal static string HelpMessageOptionFormat {
            get {
                return ResourceManager.GetString("HelpMessageOptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string HelpMessageOptionHeading {
            get {
                return ResourceManager.GetString("HelpMessageOptionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify output file (default: write to current directory).
        /// </summary>
        internal static string HelpMessageOut {
            get {
                return ResourceManager.GetString("HelpMessageOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suppress all warnings (deprecated).
        /// </summary>
        internal static string HelpMessageSuppressAllWarnings {
            get {
                return ResourceManager.GetString("HelpMessageSuppressAllWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suppress all warnings or a specific message ID
        ///            (example: -sw1011 -sw1012).
        /// </summary>
        internal static string HelpMessageSuppressWarning {
            get {
                return ResourceManager.GetString("HelpMessageSuppressWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this help information.
        /// </summary>
        internal static string HelpMessageThisHelpInfo {
            get {
                return ResourceManager.GetString("HelpMessageThisHelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to treat all warnings as errors (deprecated).
        /// </summary>
        internal static string HelpMessageTreatAllWarningsAsErrors {
            get {
                return ResourceManager.GetString("HelpMessageTreatAllWarningsAsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to treat all warnings or a specific message ID as an error
        ///            (example: -wx1011 -wx1012).
        /// </summary>
        internal static string HelpMessageTreatWarningAsError {
            get {
                return ResourceManager.GetString("HelpMessageTreatWarningAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verbose output.
        /// </summary>
        internal static string HelpMessageVerbose {
            get {
                return ResourceManager.GetString("HelpMessageVerbose", resourceCulture);
            }
        }
    }
}
