#pragma once
// Copyright (c) .NET Foundation and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information.


#define COST_PARTITION_CREATE 10000
#define COST_PARTITION_DELETE 10000

#define COST_PARTITION_USER_CREATE 10000
#define COST_PARTITION_USER_DELETE 10000

#define COST_USER_IN_PARTITION_ROLE_CREATE 10000
#define COST_USER_IN_PARTITION_ROLE_DELETE 10000

#define COST_APPLICATION_CREATE 10000
#define COST_APPLICATION_DELETE 10000

#define COST_APPLICATION_ROLE_CREATE 10000
#define COST_APPLICATION_ROLE_DELETE 10000

#define COST_USER_IN_APPLICATION_ROLE_CREATE 10000
#define COST_USER_IN_APPLICATION_ROLE_DELETE 10000

#define COST_ASSEMBLY_REGISTER   50000
#define COST_ASSEMBLY_UNREGISTER 10000

#define COST_ROLLASSIGNMENT_CREATE 10000
#define COST_ROLLASSIGNMENT_DELETE 10000

#define COST_SUBSCRIPTION_CREATE 10000
#define COST_SUBSCRIPTION_DELETE 10000
