#pragma once
// Copyright (c) .NET Foundation and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information.


const UINT COST_IIS_TRANSACTIONS = 10000;

const UINT COST_IIS_CREATEKEY = 5000;
const UINT COST_IIS_DELETEKEY = 5000;
const UINT COST_IIS_WRITEVALUE = 5000;
const UINT COST_IIS_DELETEVALUE = 5000;
const UINT COST_IIS_CREATEAPP = 5000;
const UINT COST_IIS_DELETEAPP = 5000;

const UINT COST_SQL_CREATEDB = 10000;
const UINT COST_SQL_DROPDB = 5000;
const UINT COST_SQL_CONNECTDB = 5000;
const UINT COST_SQL_STRING = 5000;

const UINT COST_PERFMON_REGISTER = 1000;
const UINT COST_PERFMON_UNREGISTER = 1000;

const UINT COST_SMB_CREATESMB = 10000;
const UINT COST_SMB_DROPSMB = 5000;

const UINT COST_CERT_ADD = 5000;
const UINT COST_CERT_DELETE = 5000;

const UINT COST_USER_ADD = 10000;
const UINT COST_USER_DELETE = 10000;

const UINT COST_PERFMONMANIFEST_REGISTER = 1000;
const UINT COST_PERFMONMANIFEST_UNREGISTER = 1000;

const UINT COST_EVENTMANIFEST_REGISTER = 1000;
const UINT COST_EVENTMANIFEST_UNREGISTER = 1000;

