//-------------------------------------------------------------------------------------------------
// <copyright file="WixStrings.Designer.cs" company="Outercurve Foundation">
//   Copyright (c) 2004, Outercurve Foundation.
//   This software is released under Microsoft Reciprocal License (MS-RL).
//   The license and further copyright text can be found in the file
//   LICENSE.TXT at the root directory of the distribution.
// </copyright>
//
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Tools.WindowsInstallerXml.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WixStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WixStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Tools.WindowsInstallerXml.VisualStudio.WixStrings", typeof(WixStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Project Files (*.wixproj);*.wixproj.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Files (*.wxs,*.wxi,*.wxl);*.wxs,*.wxi,*.wxl.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer XML.
        /// </summary>
        internal static string _120 {
            get {
                return ResourceManager.GetString("120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J8KPQCHMHKP9K8J1ICH1J8RAJDMJMEI1E2KZQ0CDE8D1I8ZCZHJAC3MMRMADRDDZCDAED1EPZCR0KRMQI0J9PHP1MRI8JHZEHKMCZ1C8I8DHPHE3EQIRQTMTK0P1HDI2.
        /// </summary>
        internal static string _150 {
            get {
                return ResourceManager.GetString("150", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _300 {
            get {
                object obj = ResourceManager.GetObject("300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Reference Files (*.dll;*.wixlib)\0*.dll;*.wixlib\0WiX Extension Files (*.dll)\0*.dll\0WiX Library Files (*.wixlib)\0*.wixlib\0All Files (*.*)\0*.*\0\0.
        /// </summary>
        internal static string AddReferenceDialogFilter {
            get {
                return ResourceManager.GetString("AddReferenceDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reference.
        /// </summary>
        internal static string AddReferenceDialogTitle {
            get {
                return ResourceManager.GetString("AddReferenceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the service of type &apos;{0}&apos; from the environment. Please log this as a bug..
        /// </summary>
        internal static string CannotGetService {
            get {
                return ResourceManager.GetString("CannotGetService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A catastrophic error has occurred and the process was terminated..
        /// </summary>
        internal static string CatastrophicError {
            get {
                return ResourceManager.GetString("CatastrophicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file successfully checked out..
        /// </summary>
        internal static string CheckoutSuccess {
            get {
                return ResourceManager.GetString("CheckoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultures.
        /// </summary>
        internal static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade failed - could not checkout file {0}..
        /// </summary>
        internal static string FailedToCheckoutFile {
            get {
                return ResourceManager.GetString("FailedToCheckoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to checkout project..
        /// </summary>
        internal static string FailedToCheckoutProject {
            get {
                return ResourceManager.GetString("FailedToCheckoutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvesting.
        /// </summary>
        internal static string HarvestCategory {
            get {
                return ResourceManager.GetString("HarvestCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressed ICEs.
        /// </summary>
        internal static string Ices {
            get {
                return ResourceManager.GetString("Ices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Path.
        /// </summary>
        internal static string IncludePath {
            get {
                return ResourceManager.GetString("IncludePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} is not a valid culture..
        /// </summary>
        internal static string InvalidCultureError {
            get {
                return ResourceManager.GetString("InvalidCultureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The {0} property cannot be empty..
        /// </summary>
        internal static string InvalidFileNameEmpty {
            get {
                return ResourceManager.GetString("InvalidFileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Invalid {0}. A file name cannot contain any of the following characters: /\:?&quot;&lt;&gt;|.
        /// </summary>
        internal static string InvalidFileNameInvalidChar {
            get {
                return ResourceManager.GetString("InvalidFileNameInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The {0} property you entered is not in a valid format..
        /// </summary>
        internal static string InvalidIce {
            get {
                return ResourceManager.GetString("InvalidIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Invalid {0}. A path cannot contain any of the following characters: *?&quot;&lt;&gt;|.
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The {0} you entered is not in a valid format. The format must follow this pattern: &lt;name&gt;=&lt;value&gt;;&lt;name&gt;.
        /// </summary>
        internal static string InvalidPreprocessorVariable {
            get {
                return ResourceManager.GetString("InvalidPreprocessorVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The {0} you entered is not in a valid format. The format must follow this pattern: &lt;number&gt;;&lt;number&gt;.
        /// </summary>
        internal static string InvalidWarnings {
            get {
                return ResourceManager.GetString("InvalidWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The {0} you entered is not in a valid format. The format must follow this pattern: &lt;name&gt;=&lt;value&gt;;&lt;name&gt;=&lt;value&gt;.
        /// </summary>
        internal static string InvalidWixVariables {
            get {
                return ResourceManager.GetString("InvalidWixVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Librarian:.
        /// </summary>
        internal static string Librarian {
            get {
                return ResourceManager.GetString("Librarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Linker:.
        /// </summary>
        internal static string Linker {
            get {
                return ResourceManager.GetString("Linker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer XML Toolset 3.8.
        /// </summary>
        internal static string OfficialName {
            get {
                return ResourceManager.GetString("OfficialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output name.
        /// </summary>
        internal static string OutputName {
            get {
                return ResourceManager.GetString("OutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path.
        /// </summary>
        internal static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
    /// <summary>
        ///   Looks up a localized string similar to Bundle (.exe).
        /// </summary>
        internal static string OutputTypeBundleDisplayName {
            get {
                return ResourceManager.GetString("OutputTypeBundleDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library (.wixlib).
        /// </summary>
        internal static string OutputTypeLibraryDisplayName {
            get {
                return ResourceManager.GetString("OutputTypeLibraryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module (.msm).
        /// </summary>
        internal static string OutputTypeModuleDisplayName {
            get {
                return ResourceManager.GetString("OutputTypeModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package (.msi).
        /// </summary>
        internal static string OutputTypePackageDisplayName {
            get {
                return ResourceManager.GetString("OutputTypePackageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessor variables.
        /// </summary>
        internal static string PreprocessorVariables {
            get {
                return ResourceManager.GetString("PreprocessorVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer XML Toolset {0} {1}
        ///   Copyright (c) Xxx
        /// </summary>
        internal static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ProjectFileIcon {
            get {
                object obj = ResourceManager.GetObject("ProjectFileIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &amp;Properties....
        /// </summary>
        internal static string ProjectPropertiesCommand {
            get {
                return ResourceManager.GetString("ProjectPropertiesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file is read-only, attempting to check-out if under source control.
        /// </summary>
        internal static string ReadOnlyFile {
            get {
                return ResourceManager.GetString("ReadOnlyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Path.
        /// </summary>
        internal static string ReferencePath {
            get {
                return ResourceManager.GetString("ReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest.
        /// </summary>
        internal static string RefHarvest {
            get {
                return ResourceManager.GetString("RefHarvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not to use heat.exe to generate authoring for this project reference..
        /// </summary>
        internal static string RefHarvestDescription {
            get {
                return ResourceManager.GetString("RefHarvestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Output Groups.
        /// </summary>
        internal static string RefProjectOutputGroups {
            get {
                return ResourceManager.GetString("RefProjectOutputGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project output groups to harvest from this project..
        /// </summary>
        internal static string RefProjectOutputGroupsDescription {
            get {
                return ResourceManager.GetString("RefProjectOutputGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Id.
        /// </summary>
        internal static string RefTargetDir {
            get {
                return ResourceManager.GetString("RefTargetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory Id where the harvested components will be placed..
        /// </summary>
        internal static string RefTargetDirDescription {
            get {
                return ResourceManager.GetString("RefTargetDirDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file was checked out and is already upgraded..
        /// </summary>
        internal static string UpgradeNoNeedToUpgradeAfterCheckout {
            get {
                return ResourceManager.GetString("UpgradeNoNeedToUpgradeAfterCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressed warnings.
        /// </summary>
        internal static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Events.
        /// </summary>
        internal static string WixBuildEventsPropertyPageName {
            get {
                return ResourceManager.GetString("WixBuildEventsPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler.
        /// </summary>
        internal static string WixCompilerPropertyPageName {
            get {
                return ResourceManager.GetString("WixCompilerPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Extension Reference.
        /// </summary>
        internal static string WixExtensionReferenceProperties {
            get {
                return ResourceManager.GetString("WixExtensionReferenceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of the WiX extension..
        /// </summary>
        internal static string WixExtensionReferenceVersionDescription {
            get {
                return ResourceManager.GetString("WixExtensionReferenceVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string WixExtensionReferenceVersionDisplayName {
            get {
                return ResourceManager.GetString("WixExtensionReferenceVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string WixInstallerPropertyPageName {
            get {
                return ResourceManager.GetString("WixInstallerPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarian.
        /// </summary>
        internal static string WixLibrarianPropertyPageName {
            get {
                return ResourceManager.GetString("WixLibrarianPropertyPageName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon WixLibraryProjectIcon {
            get {
                object obj = ResourceManager.GetObject("WixLibraryProjectIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Library Reference.
        /// </summary>
        internal static string WixLibraryReferenceProperties {
            get {
                return ResourceManager.GetString("WixLibraryReferenceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker.
        /// </summary>
        internal static string WixLinkerPropertyPageName {
            get {
                return ResourceManager.GetString("WixLinkerPropertyPageName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon WixMergeModuleProjectIcon {
            get {
                object obj = ResourceManager.GetObject("WixMergeModuleProjectIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
    internal static System.Drawing.Icon WixBundleProjectIcon {
            get {
                object obj = ResourceManager.GetObject("WixBundleProjectIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        internal static string WixPathsPropertyPageName {
            get {
                return ResourceManager.GetString("WixPathsPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX Project Reference.
        /// </summary>
        internal static string WixProjectReferenceProperties {
            get {
                return ResourceManager.GetString("WixProjectReferenceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to {0} could not be added. Please make sure that the file is accessible, and that it is a valid WiX reference..
        /// </summary>
        internal static string WixReferenceInvalid {
            get {
                return ResourceManager.GetString("WixReferenceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string WixReferencesFolderName {
            get {
                return ResourceManager.GetString("WixReferencesFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string WixSettingsPropertyPageName {
            get {
                return ResourceManager.GetString("WixSettingsPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the WiX targets file has been updated..
        /// </summary>
        internal static string WixTargetsPathUpdated {
            get {
                return ResourceManager.GetString("WixTargetsPathUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Settings.
        /// </summary>
        internal static string WixToolsSettingsPropertyPageName {
            get {
                return ResourceManager.GetString("WixToolsSettingsPropertyPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wix variables.
        /// </summary>
        internal static string WixVariables {
            get {
                return ResourceManager.GetString("WixVariables", resourceCulture);
            }
        }
    }
}
